import 'package:ingrain/core/error/app_error.dart';
import 'package:ingrain/core/network/api_client.dart';
import 'package:ingrain/features/content/data/youtube_transcript_fetcher.dart';

/// Japanese captions through the HitaruJP API (`/youtube/transcripts/{id}`).
///
/// Used on web, where the browser blocks calls to YouTube (CORS). Mobile keeps
/// fetching captions directly with [YoutubeTranscriptFetcher].
class RemoteYoutubeTranscriptFetcher implements YoutubeTranscriptFetcher {
  final ApiClient _api;

  RemoteYoutubeTranscriptFetcher(this._api);

  @override
  Future<YoutubeTranscriptResult> fetch(String videoId) async {
    try {
      final json = await _api.get('/youtube/transcripts/$videoId') as Map;
      return YoutubeTranscriptResult(
        // Unknown here; the caller keeps the length it already has.
        durationSeconds: 0,
        transcriptText: json['srt'] as String?,
        hasAutoGenerated: json['isGenerated'] as bool? ?? false,
      );
    } on ApiException catch (error) {
      // No Japanese captions: a normal answer, not a failure.
      if (error.error.type == AppErrorType.notFound) {
        return const YoutubeTranscriptResult(durationSeconds: 0);
      }
      throw YoutubeTranscriptException(
        error.error.message ?? 'Could not fetch the transcript.',
      );
    }
  }
}
