import 'package:collection/collection.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

class YoutubeTranscriptFetcher {
  final YoutubeExplode _youtubeExplode = YoutubeExplode();

  Future<YoutubeTranscriptResult> fetch(String videoId) async {
    try {
      final video = await _youtubeExplode.videos.get(videoId);
      final duration = video.duration?.inSeconds ?? 0;

      final manifest = await _youtubeExplode.videos.closedCaptions.getManifest(
        videoId,
      );

      // Find the best track: prefer manual, then auto-generated
      final tracks = manifest.tracks;
      ClosedCaptionTrackInfo? track;

      // First try to find a manual track in English or any language
      track = tracks.firstWhereOrNull(
        (t) => !t.isAutoGenerated && t.language.code == 'en',
      );

      // If no English manual, try any manual track
      track ??= tracks.firstWhereOrNull((t) => !t.isAutoGenerated);

      // Fall back to auto-generated
      track ??= tracks.firstWhereOrNull(
        (t) => t.isAutoGenerated && t.language.code == 'en',
      );
      track ??= tracks.firstWhereOrNull((t) => t.isAutoGenerated);

      String? transcriptText;
      if (track != null) {
        final captionsTrack = await _youtubeExplode.videos.closedCaptions.get(
          track,
        );
        transcriptText = _captionsToText(captionsTrack);
      }

      return YoutubeTranscriptResult(
        durationSeconds: duration,
        transcriptText: transcriptText,
        hasAutoGenerated: track?.isAutoGenerated ?? false,
      );
    } on YoutubeExplodeException catch (e) {
      throw YoutubeTranscriptException('YouTube error: ${e.message}');
    } catch (e) {
      throw YoutubeTranscriptException('Failed to fetch transcript: $e');
    }
  }

  String _captionsToText(ClosedCaptionTrack captionsTrack) {
    final buffer = StringBuffer();
    final captions = captionsTrack.captions;
    for (int i = 0; i < captions.length; i++) {
      final caption = captions[i];
      final start = _formatTime(caption.offset);
      final end = _formatTime(caption.end);
      buffer.write('$start --> $end\n${caption.text}');
      if (i < captions.length - 1) {
        buffer.write('\n\n');
      }
    }
    return buffer.toString();
  }

  String _formatTime(Duration d) {
    final hours = d.inHours.toString().padLeft(2, '0');
    final minutes = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final seconds = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    final milliseconds = d.inMilliseconds
        .remainder(1000)
        .toString()
        .padLeft(3, '0');
    return '$hours:$minutes:$seconds,$milliseconds';
  }
}

class YoutubeTranscriptResult {
  final int durationSeconds;
  final String? transcriptText;
  final bool hasAutoGenerated;

  const YoutubeTranscriptResult({
    required this.durationSeconds,
    this.transcriptText,
    this.hasAutoGenerated = false,
  });
}

class YoutubeTranscriptException implements Exception {
  final String message;
  const YoutubeTranscriptException(this.message);

  @override
  String toString() => message;
}
