import 'package:flutter_test/flutter_test.dart';
import 'package:ingrain/features/vocabulary/data/asset_dictionary_loader.dart';

/// Guards the asset generated by `tool/build_dictionary.py`.
///
/// The data is produced offline, so this is the only check that the committed
/// file still parses, keeps its attribution and actually covers everyday words.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('the bundled dictionary loads and resolves everyday words', () async {
    final index = await const AssetDictionaryLoader().load();

    expect(index.length, greaterThan(1000));

    final cat = index.lookup('猫');
    expect(cat, isNotNull);
    expect(cat!.reading, 'ねこ');
    expect(cat.pos, 'noun');
    expect(cat.meanings, isNotEmpty);

    // Readable by reading as well as by written form.
    expect(index.lookup('ねこ')?.surface, '猫');

    for (final word in const ['日本語', '時間', '今日', '学生', '世界', '本']) {
      final entry = index.lookup(word);
      expect(entry, isNotNull, reason: '$word should be in the asset');
      expect(entry!.reading, isNotEmpty);
      expect(entry.meanings, isNotEmpty);
    }
  });

  test('unknown words simply miss', () async {
    final index = await const AssetDictionaryLoader().load();

    expect(index.lookup('犬'), isNotNull);
    expect(index.lookup('ゑゐ冴散在薫'), isNull);
    expect(index.lookup(''), isNull);
    expect(index.contains('ゑゐ冴散在薫'), isFalse);
  });
}
