// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzqO6SLgZaP7uSyhRcaJcCMaSH5Qi7Lqs',
    appId: '1:29208930706:web:c307a40073df9bdea6394b',
    messagingSenderId: '29208930706',
    projectId: 'ingrain-58270',
    authDomain: 'ingrain-58270.firebaseapp.com',
    storageBucket: 'ingrain-58270.firebasestorage.app',
    measurementId: 'G-NS564CXV3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6oE5E6lFk9NBIygQBlHr-04fkcEXc83U',
    appId: '1:29208930706:android:d135362fd098a173a6394b',
    messagingSenderId: '29208930706',
    projectId: 'ingrain-58270',
    storageBucket: 'ingrain-58270.firebasestorage.app',
  );
}
