import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:ingrain/core/network/api_client.dart';
import 'package:ingrain/features/content/data/remote_video_search_repository.dart';
import 'package:ingrain/features/content/data/remote_youtube_transcript_fetcher.dart';
import 'package:ingrain/features/content/data/youtube_transcript_fetcher.dart';

// The web app searches YouTube through the API, since browsers block calls to
// youtube.com directly.
RemoteVideoSearchRepository repository(MockClientHandler handler) =>
    RemoteVideoSearchRepository(
      ApiClient(
        client: MockClient(handler),
        idToken: () async => 'token',
        baseUrl: 'https://api.example.test',
      ),
    );

http.Response json(Object body, [int status = 200]) =>
    http.Response.bytes(utf8.encode(jsonEncode(body)), status);

void main() {
  test('searches through the API and maps the results', () async {
    late Uri asked;
    final results = await repository((request) async {
      asked = request.url;
      return json({
        'items': [
          {
            'videoId': 'drTGtJEvRCA',
            'title': 'Nihongo con Teppei #1',
            'channelTitle': 'Teppei',
            'durationSeconds': 235,
            'thumbnailUrl': 'https://i.ytimg.com/vi/drTGtJEvRCA/mqdefault.jpg',
          },
        ],
      });
    }).search('teppei');

    expect(asked.path, '/youtube/search');
    expect(asked.queryParameters['q'], 'teppei');
    final video = results.single;
    expect(video.videoId, 'drTGtJEvRCA');
    expect(video.channelTitle, 'Teppei');
    expect(video.duration, const Duration(seconds: 235));
    expect(video.url, 'https://www.youtube.com/watch?v=drTGtJEvRCA');
  });

  test(
    'a link lookup returns the video, or null when it does not exist',
    () async {
      final found = await repository(
        (_) async => json({
          'videoId': 'drTGtJEvRCA',
          'title': 'Teppei',
          'thumbnailUrl': 'https://i.ytimg.com/vi/drTGtJEvRCA/mqdefault.jpg',
        }),
      ).lookup('drTGtJEvRCA');
      final missing = await repository(
        (_) async => json({'detail': 'video not found'}, 404),
      ).lookup('missing0000');

      expect(found?.duration, isNull, reason: 'the player learns it on load');
      expect(missing, isNull);
    },
  );

  test('a YouTube outage surfaces as an error the screen can show', () async {
    await expectLater(
      repository((_) async => json({'detail': 'down'}, 502)).search('x'),
      throwsA(isA<ApiException>()),
    );
  });

  group('transcripts on web', () {
    RemoteYoutubeTranscriptFetcher fetcher(MockClientHandler handler) =>
        RemoteYoutubeTranscriptFetcher(
          ApiClient(
            client: MockClient(handler),
            idToken: () async => 'token',
            baseUrl: 'https://api.example.test',
          ),
        );

    test('returns the SRT the API sends', () async {
      late Uri asked;
      final result = await fetcher((request) async {
        asked = request.url;
        return json({
          'videoId': 'NlPLRfQwrD8',
          'language': 'ja',
          'isGenerated': false,
          'srt': '00:00:31,800 --> 00:00:33,866\n日本語教師のしゅんです',
        });
      }).fetch('NlPLRfQwrD8');

      expect(asked.path, '/youtube/transcripts/NlPLRfQwrD8');
      expect(result.transcriptText, contains('日本語教師'));
      expect(result.hasAutoGenerated, isFalse);
    });

    test('no Japanese captions is an empty result, not an error', () async {
      final result = await fetcher(
        (_) async => json({'detail': 'no Japanese captions'}, 404),
      ).fetch('noJapanese1');

      expect(result.transcriptText, isNull);
    });

    test('a blocked or failed fetch is a transcript error', () async {
      await expectLater(
        fetcher((_) async => json({'detail': 'blocked'}, 503)).fetch('x'),
        throwsA(isA<YoutubeTranscriptException>()),
      );
    });
  });
}
