import 'package:flutter_test/flutter_test.dart';
import 'package:ingrain/features/content/data/youtube_transcript_fetcher.dart';

typedef Track = ({String code, bool auto});

Track? _pick(List<Track> tracks) => YoutubeTranscriptFetcher.pickJapaneseTrack(
  tracks,
  languageCode: (t) => t.code,
  isAutoGenerated: (t) => t.auto,
);

void main() {
  test('never picks English, even a hand-made English track', () {
    final track = _pick([(code: 'en', auto: false), (code: 'ja', auto: true)]);

    expect(track, (code: 'ja', auto: true));
  });

  test('prefers hand-made Japanese captions over auto-generated', () {
    final track = _pick([(code: 'ja', auto: true), (code: 'ja', auto: false)]);

    expect(track?.auto, isFalse);
  });

  test('accepts regional Japanese codes', () {
    expect(_pick([(code: 'ja-JP', auto: false)])?.code, 'ja-JP');
  });

  test('is null when there is no Japanese track', () {
    expect(
      _pick([(code: 'en', auto: false), (code: 'jv', auto: false)]),
      isNull,
    );
    expect(_pick(const []), isNull);
  });
}
