import 'package:flutter/material.dart';

/// The HitaruJP logo, rendered from the same artwork as the launcher icon
/// (`branding/`, regenerated by `tool/generate_icons.sh`).
class AppLogo extends StatelessWidget {
  final double size;
  final bool _tile;

  /// The simplified mark (head, brain and 浸) for small places such as the
  /// sidebar, where the floating symbols of the full icon would be noise.
  const AppLogo.mark({super.key, this.size = 40}) : _tile = false;

  /// The full icon on a white rounded tile, as it appears on a home screen.
  const AppLogo.tile({super.key, this.size = 96}) : _tile = true;

  @override
  Widget build(BuildContext context) {
    final image = Image.asset(
      _tile ? 'assets/branding/logo.png' : 'assets/branding/logo_mark.png',
      width: _tile ? size * 0.82 : size,
      height: _tile ? size * 0.82 : size,
      filterQuality: FilterQuality.medium,
      semanticLabel: 'HitaruJP',
    );
    if (!_tile) return image;
    return Container(
      width: size,
      height: size,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(size * 0.22),
        boxShadow: const [
          BoxShadow(
            color: Color(0x1F12305E),
            blurRadius: 18,
            offset: Offset(0, 6),
          ),
        ],
      ),
      child: image,
    );
  }
}
